credentials:
  usernames:
    capstone:
      email: max@heilingbrunner.info
      name: Gustavo and Pepe
      password: $2b$12$BWDKGOfmNxROdskxk/hkuugnyxC0PoE5OjmqUIKqWFhSfPgynNWou # Pandas2020!
cookie:
  expiry_days: 30
  key: JHSF&%/&S$& 
  name: token
preauthorized:
  emails:
  - gustavom@faculty.ie.edu
  - jgarciah@faculty.ie.edu
api_key:
  key: IEMCSBT23